name: Assign Copilot on Label

on:
  issues:
    types: [labeled]

jobs:
  assign-copilot:
    if: contains(github.event.label.name, 'copilot label')
    runs-on: ubuntu-latest
    steps:
      - name: Assign Copilot
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number,
              assignees: ['github-copilot[bot]']
            })
